name: EPG Generator

on:
  schedule:
    - cron: '0 0 */2 * *'  # 每兩天 UTC 0 點運行
  workflow_dispatch:

jobs:
  generate-epg:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'

    - name: Install Chrome dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y chromium-browser chromium-chromedriver
        sudo ln -s /usr/bin/chromium-browser /usr/bin/google-chrome

    - name: Install Python dependencies
      run: |
        python -m pip install --upgrade pip
        pip install requests pytz loguru cloudscraper selenium webdriver-manager beautifulsoup4 xmltodict

    - name: Create output directory
      run: mkdir -p output

    - name: Run Get_Channel.py
      run: python Get_Channel.py
      working-directory: ./scripts
      env:
        PYTHONUNBUFFERED: 1  # 確保日誌實時輸出

    - name: Run Make_EPG.py
      run: |
        # 隨機延遲減少並發檢測風險
        sleep $((RANDOM % 30))
        python Make_EPG.py
      working-directory: ./scripts
      env:
        PYTHONUNBUFFERED: 1  # 確保日誌實時輸出

    - name: Commit and Push Changes
      run: |
        git config --global user.name "github-actions[bot]"
        git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
        git add output/*
        git commit -m "Auto-update EPG data (output)"
        git push
