name: EPG Generator

on:
  schedule:
    - cron: '0 0 */2 * *'
  workflow_dispatch:

jobs:
  generate-epg:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'

    - name: Install Chrome dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y chromium-browser chromium-chromedriver
        sudo rm -f /usr/bin/google-chrome
        sudo ln -s /usr/bin/chromium-browser /usr/bin/google-chrome

    - name: Install Python dependencies
      run: |
        python -m pip install --upgrade pip
        pip install requests pytz loguru cloudscraper selenium webdriver-manager beautifulsoup4 xmltodict

    - name: Create output directory
      run: mkdir -p output

    - name: Run Get_Channel.py
      run: python scripts/Get_Channel.py  

    - name: Run Make_EPG.py
      run: |
        sleep $((RANDOM % 30))
        python scripts/Make_EPG.py  
      env:
        PYTHONUNBUFFERED: 1

    - name: Fix permissions
      run: sudo chown -R $USER:$USER .  

    - name: Commit and Push Changes
      run: |
        git config --global user.name "github-actions[bot]"
        git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
        git add output/*
        git commit -m "Auto-update EPG data (output)"
        git push

    - name: Verify output files
      run: |
        ls -la output
        cat output/epg_generator.log
      if: always()
