name: EPG Generator

on:
  schedule:
    - cron: '0 0 */2 * *'  # 每兩天 UTC 0 點運行
  workflow_dispatch:

jobs:
  generate-epg:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install requests pytz loguru selenium webdriver-manager

    - name: Install Chrome dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y libnss3 libnspr4 libatk1.0-0 libatk-bridge2.0-0 \
        libcups2 libdrm2 libxkbcommon0 libxcomposite1 libxdamage1 libxfixes3 \
        libxrandr2 libgbm1 libasound2

    - name: Create output directory
      run: mkdir -p output

    - name: Run Get_Channel.py
      run: python scripts/Get_Channel.py

    - name: Run Make_EPG.py
      run: python scripts/Make_EPG.py

    - name: Commit and Push Changes
      run: |
        git config --global user.name "github-actions[bot]"
        git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
        git add output/*
        git commit -m "Auto-update EPG data (output)"
        git push
