name: Daily Hami EPG Update
on:
  schedule:
    - cron: '0 0 * * *'  # 每天UTC時間00:00執行（台北時間08:00）
  workflow_dispatch:

jobs:
  generate-epg:
    runs-on: ubuntu-latest
    timeout-minutes: 30  # 設置超時時間
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
          
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests pytz loguru
          
      - name: Run EPG Generator
        run: python scripts/Hami.py
        
      - name: Upload EPG file
        uses: actions/upload-artifact@v3
        with:
          name: hami-epg
          path: output/hami.xml
          
      - name: Commit and push EPG
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add output/hami.xml
          git commit -m "Auto-update Hami EPG"
          git push
