name: EPG Generator

on:
  schedule:
    # 每天淩晨2點運行 (UTC時間)
    - cron: '0 18 * * *'
  workflow_dispatch:

jobs:
  generate-epg:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
      
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install requests beautifulsoup4 pytz
        
    - name: Generate EPG
      run: |
        mkdir -p output
        python scripts/ofiii_epg.py
        
    - name: Commit and push changes
      run: |
        git config --local user.email "41898282+github-actions[bot]@users.noreply.github.com"
        git config --local user.name "GitHub Actions"
        git add output/ofiii.xml
        git commit -m "自動更新EPG數據: $(date +'%Y-%m-%d %H:%M:%S')"
        git push
