name: TBC EPG Generator

on:
  schedule:
    # 每天在UTC時間16:00
    - cron: '0 16 * * *'
  workflow_dispatch:  # 允許手動觸發

jobs:
  generate_epg:
    runs-on: ubuntu-latest
    timeout-minutes: 30  # 設置超時時間

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests beautifulsoup4 pytz

      - name: Run TBC EPG Generator
        run: python scripts/tbc_epg.py

      - name: Commit and push changes
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add docs/tbc_epg.xml
          git diff-index --quiet HEAD || git commit -m "Auto update TBC EPG data"
          git push
