name: TBC EPG Generator

on:
  schedule:
    # 每天UTC時間18:00執行 (台灣時間02:00)
    - cron: "0 18 * * *"
  workflow_dispatch:

jobs:
  generate-epg:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: "3.10"
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        
    - name: Run EPG generator
      run: python scripts/tbc_epg.py
      
    - name: Commit EPG file
      run: |
        git config user.name "GitHub Actions"
        git config user.email "actions@github.com"
        git add epg_output/tbc.xml
        git commit -m "Auto update TBC EPG data"
        git push
