name: Daily TBC EPG Update

on:
  schedule:
    - cron: '0 2 * * *'
  workflow_dispatch:

jobs:
  update_epg:
    runs-on: ubuntu-latest
    timeout-minutes: 30  # 設置超時時間
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      
    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: '3.10'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install requests beautifulsoup4 pytz urllib3
        
    - name: Run EPG Scraper
      run: |
        cd scripts
        python tbc.py
        
    - name: Commit and push changes
      run: |
        git config --global user.name 'GitHub Actions'
        git config --global user.email 'actions@github.com'
        git add output/tbc.xml
        git commit -m "自動更新TBC EPG數據 [skip ci]" || echo "無變更可提交"
        git push
