name: Update 4gtv Cookie

on:
  schedule:
    - cron: '0 16 * * *'  # 每天台灣時間 0:00 執行 (UTC+8 所以是 UTC 16:00)
  workflow_dispatch:

jobs:
  update:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Python 3.11
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: pip install cloudscraper

      - name: Run fetch_cookie.py
        run: python scripts/fetch_cookie.py

      - name: Commit and push updated cookie.json
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add output/cookie.json
          git diff --cached --quiet || (git commit -m "Update cookie.json `date +'%F %T'`" && git push)
